routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {\

Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingPage');
Route::get('/about', [App\Http\Controllers\LandingPageController::class, 'about'])->name('aboutUs');

Route::get('/login', function () {
    return view('signin');
});
Route::get('/register', function () {
    return view('signup');
})->name('Sign Up');


Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
Route::get('/dashboard/{work}', [App\Http\Controllers\DashboardController::class, 'show'])->name('details');
Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile.index');
Route::put('/profile/{user}', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');
Route::put('/profile/{user}/address', [App\Http\Controllers\ProfileController::class, 'updateAddress'])->name('profile.address');
Route::put('/profile/{user}/password', [App\Http\Controllers\ProfileController::class, 'updatePassword'])->name('profile.updatePassword');
// Route::resource('profile', App\Http\Controllers\ProfileController::class )->only('index','update');
Route::get('/workImages/{id}', [\App\Http\Controllers\WorkImagesController::class, 'show'])->name('workImages.show');
Route::put('/workImages/{id}', [\App\Http\Controllers\WorkImagesController::class, 'update'])->name('workImages.update');
Route::delete('/workImages', [\App\Http\Controllers\WorkImagesController::class, 'destroy'])->name('workImages.destroy');

Route::resource('works', App\Http\Controllers\WorkController::class )->except('show','edit');
Route::get('works/accepted', [App\Http\Controllers\WorkController::class, 'accepted'])->name('works.accepted');
Route::get('works/finished', [App\Http\Controllers\WorkController::class, 'finishedWorks'])->name('works.finishedWorks');
Route::get('works/{id}', [App\Http\Controllers\WorkController::class, 'getDetails'])->name('getDetails'); //used by all to show details modal
Route::get('/works/fetch-service/{id}', [App\Http\Controllers\WorkController::class, 'fetchService']); //used by admin and cust to req new works

Route::get('/sendMail', [App\Http\Controllers\DashboardController::class, 'sendEmail']); //test sending new Work to admin
Route::get('/assignEmail', [App\Http\Controllers\DashboardController::class, 'assignEmail']); //test sending assigned Work to employee


Route::group(['middleware' => ['role:admin|employee']], function(){
    Route::get('/works/getSavedAddress/{id}', [App\Http\Controllers\WorkController::class, 'getSavedAddress']);
    Route::get('/works/status/{id}', [App\Http\Controllers\WorkController::class, 'changeWorkStatus'])->name('works.status');
    Route::put('/works/{id}/edit', [App\Http\Controllers\WorkController::class, 'edit'])->name('works.edit');
    Route::put('/works/{id}/finish', [App\Http\Controllers\WorkController::class, 'finish'])->name('works.finish'); //used by employee to finish works
    Route::post('/works/{id}/add-photo', [App\Http\Controllers\WorkController::class, 'addPhoto']); 

    Route::get('/exportToday', [App\Http\Controllers\DashboardController::class, 'exportToday'])->name('export.today');
    Route::get('/exportWork/{id}', [App\Http\Controllers\DashboardController::class, 'exportWork'])->name('export.work');
});

Route::group(['middleware' => ['role:admin']], function () {

    Route::get('/landing', [App\Http\Controllers\SettingController::class, 'index'])->name('admin.landing');
    Route::post('/landing', [App\Http\Controllers\SettingController::class, 'update'])->name('admin.landing.update');
    Route::post('/landing/service', [App\Http\Controllers\SettingController::class, 'storeService'])->name('admin.service.store');
    Route::get('/landing/service/{id}', [App\Http\Controllers\SettingController::class, 'edit'])->name('admin.service.edit');
    Route::post('/landing/service/{id}', [App\Http\Controllers\SettingController::class, 'updateService'])->name('admin.service.update');
    // Route::post('/landing/service/{id}', [App\Http\Controllers\SettingController::class, 'updateService'])->name('admin.service.update');
    Route::delete('/landing/{id}', [App\Http\Controllers\SettingController::class, 'destroy'])->name('admin.service.delete');
    
    Route::resource('services', App\Http\Controllers\ServiceController::class );
    Route::post('/service', [App\Http\Controllers\ServiceController::class, 'storeCategory'])->name('categories.store');
    Route::post('/service/{id}', [App\Http\Controllers\ServiceController::class, 'updateCategory'])->name('categories.update');
    // Route::put('/service', [App\Http\Controllers\ServiceController::class, 'update'])->name('admin.service.update');
    
    // Route::resource('employees', App\Http\Controllers\EmployeeController::class);
    Route::get('/employees', [App\Http\Controllers\EmployeeController::class, 'index'])->name('employees.index');
    Route::post('/employees', [App\Http\Controllers\EmployeeController::class, 'store'])->name('employees.store');
    Route::put('/employees/{id}', [App\Http\Controllers\EmployeeController::class, 'update'])->name('employees.update');
    Route::get('/employees/status/{id}', [App\Http\Controllers\EmployeeController::class, 'changeStatus'])->name('employees.status');
    
    Route::get('/customers', [App\Http\Controllers\CustomersController::class, 'index'])->name('customers.index');
    Route::post('/customers', [App\Http\Controllers\CustomersController::class, 'store'])->name('customers.store');
    Route::put('/customers/{id}', [App\Http\Controllers\CustomersController::class, 'update'])->name('customers.update');

    Route::get('/reporting', [App\Http\Controllers\ReportController::class, 'index'])->name('admin.reporting');
    Route::get('/reporting/{start}/{end}', [App\Http\Controllers\ReportController::class, 'getReport']);
    Route::get('/export/{start}/{end}', [App\Http\Controllers\ReportController::class, 'exportExcel']);
});

Route::get('migrate',function(){
    Artisan::call('migrate', ['--force' => true]);
});

Route::get('rollback',function(){
    Artisan::call('migrate:rollback', ['--force' => true]);
 });

 Route::get('reboot',function(){
    Artisan::call('view:clear', ['--force' => true]);
    Artisan::call('route:clear', ['--force' => true]);
    Artisan::call('config:clear', ['--force' => true]);
    Artisan::call('cache:clear', ['--force' => true]);
    Artisan::call('key:generate', ['--force' => true]);
  });

  Route::get('seed', function(){
    Artisan::call('db:seed', array('--class' => 'PermissionsAssign', '--force' => true));
  });

resources/views/partials/alert.blade.php
@if (Session::has('message'))
    <div class="position-fixed top-1 end-1 z-index-sticky">
        <div class="toast fade show p-2 mt-2 bg-white" role="alert" aria-live="assertive" id="dangerToast" aria-atomic="true">
            <div class="toast-header border-0">
              <i class="material-icons text-success me-2">campaign</i>
              <span class="me-auto text-gradient text-success font-weight-bold">Success</span>
              {{-- <small class="text-body">11 mins ago</small> --}}
              <i class="fas fa-times text-md ms-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
            </div>
            <hr class="horizontal dark m-0">
            <div class="toast-body">
                {{ Session::get('message') }}
            </div>
        </div>
    </div>
@elseif(Session::has('error'))
    <div class="position-fixed top-1 end-1 z-index-sticky">
        <div class="toast fade show p-2 mt-2 bg-white" role="alert" aria-live="assertive" id="dangerToast" aria-atomic="true">
            <div class="toast-header border-0">
              <i class="material-icons text-danger me-2">campaign</i>
              <span class="me-auto text-gradient text-danger font-weight-bold">Alert</span>
              {{-- <small class="text-body">11 mins ago</small> --}}
              <i class="fas fa-times text-md ms-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
            </div>
            <hr class="horizontal dark m-0">
            <div class="toast-body">
                {{ Session::get('errorsMsg') }}
            </div>
        </div>
    </div>
@endif
<!-- Error Toast -->
<div class="position-fixed top-1 end-1 z-index-sticky">
    @if($errors->any())
        @foreach ($errors->all() as $error)
            <div class="toast fade show p-2 mt-2 bg-white" role="alert" aria-live="assertive" id="dangerToast" aria-atomic="true">
                <div class="toast-header border-0">
                    <i class="material-icons text-danger me-2">campaign</i>
                    <span class="me-auto text-gradient text-danger font-weight-bold">Aborted</span>
                    <i class="fas fa-times text-md ms-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
                </div>
                <hr class="horizontal dark m-0">
                <div class="toast-body">
                    <strong>{{ $error }}</strong>
                </div>
            </div>
        @endforeach
    @endif
  </div>

resources/views/partials/navbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 border-radius-xl position-sticky mt-4 top-1 z-index-sticky blur shadow-blur left-auto" id="navbarBlur" data-scroll="true" navbar-scroll="true">
{{-- <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true"> --}}
    <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
          <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
          <li class="breadcrumb-item text-sm text-dark active" aria-current="page">{{ Route::current()->getName(); }}</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">{{ Route::current()->getName(); }}</h6>
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
          <div class="input-group input-group-outline">
            {{-- <label class="form-label">Type here...</label>
            <input type="text" class="form-control"> --}}
            <h5>{{ date('F d, Y') }}</h5>
          </div>
        </div>
        <ul class="navbar-nav justify-content-end">
          @can('access admin page')
            <li class="nav-item d-xl-none ps-3 d-flex align-items-center m-3">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
          @endcan
          <li class="nav-item dropdown pe-2 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-cog cursor-pointer"></i>
            </a>
            <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
              <li class="mb-2">
                <a class="dropdown-item border-radius-md" href="/dashboard">
                  <div class="d-flex py-1">
                    <div class="avatar avatar-sm bg-gradient-secondary me-3 my-auto">
                      <i class="material-icons opacity-10">home</i>
                    </div>
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="text-sm font-weight-normal mb-1">
                        Dashboard
                      </h6>
                    </div>
                  </div>
                </a>
              </li>
              <li class="mb-2">
                <a class="dropdown-item border-radius-md" href="{{ route('profile.index') }}">
                  <div class="d-flex py-1">
                    <div class="avatar avatar-sm bg-gradient-secondary me-3 my-auto">
                      <i class="material-icons opacity-10">person</i>
                    </div>
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="text-sm font-weight-normal mb-1">
                        Profile
                      </h6>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a class="dropdown-item border-radius-md" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                  <div class="d-flex py-1">
                    <div class="avatar avatar-sm bg-gradient-secondary me-3 my-auto">
                      <i class="material-icons opacity-10">logout</i>
                    </div>
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="text-sm font-weight-normal mb-1">
                        Sign Out
                      </h6>
                    </div>
                  </div>
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                  @csrf
                </form>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>
<!-- End Navbar -->

resources/views/partials/navbarLand.blade.php
<nav
    class="navbar navbar-expand-lg navbar-dark bg-gradient-dark z-index-3 py-3">
    <div class="container">
      <a class="navbar-brand text-white d-lg-block d-none" href="/" rel="tooltip" title="Home Page">
        <i class="material-icons">home</i>
      </a>
      <a class="navbar-brand text-white d-lg-block d-none" href="/dashboard" rel="tooltip" title="My Dashboard" data-placement="bottom" target="_blank">
        {{ $show['site_title']->value }}
      </a>
      <a class="navbar-brand text-white d-lg-block d-none mx-auto" href="/about" rel="tooltip" title="About Us" data-placement="bottom">
        About Us
      </a>
      <a class="mx-auto"></a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0" id="navigation">
        <ul class="navbar-nav d-lg-none d-block">
          <li class="nav-item mx-2">
            <a href="/" class="btn btn-sm mb-0 me-1 mt-2 mt-md-0">
              <p class="d-inline text-sm z-index-1 text-white font-weight-bold">Home</p>
            </a>
          </li>
          <li class="nav-item mx-2">
            <a href="/dashboard" class="btn btn-sm mb-0 me-1 mt-2 mt-md-0">
              <p class="d-inline text-sm z-index-1 text-white font-weight-bold">{{ $show['site_title']->value }}</p>
            </a>
          </li>
          <li class="nav-item mx-2">
            <a href="/about" class="btn btn-sm mb-0 me-1 mt-2 mt-md-0">
              <p class="d-inline text-sm z-index-1 text-white font-weight-bold">About Us</p>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav d-lg-block d-none mx-auto">
          <li class="nav-item mx-2">
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-hover">
          <li class="nav-item mx-2">
            <a href="/#register" class="btn btn-sm mb-0 me-1 mt-2 mt-md-0">
              <p class="d-inline text-sm z-index-1 text-white font-weight-bold">Register</p>
            </a>
          </li>
          <li class="nav-item mx-2">
            <a href="/login" class="btn btn-sm mb-0 me-1 mt-2 mt-md-0">
              <p class="d-inline text-sm z-index-1 text-white font-weight-bold">Login</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

resources/views/partials/sidebar.blade.php
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark" id="sidenav-main">
<div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href=" /dashboard " target="_blank">
    <img src="../img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
    <span class="ms-1 font-weight-bold text-white">WeLikeWork.ca</span>
    </a>
</div>
<hr class="horizontal light mt-0 mb-2">
<div class="collapse navbar-collapse w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">
        @can('access admin page')
        <li class="nav-item">
            <a class="nav-link text-white" href="/dashboard">
                <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="material-icons opacity-10">dashboard</i>
                </div>
                <span class="nav-link-text ms-1">My Work</span>
            </a>
        </li>
        <li class="nav-item mt-3">
            <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Work</h6>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="/works">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">work</i>
            </div>
            <span class="nav-link-text ms-1">Incoming Work</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="{{ route('works.accepted') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">fact_check</i>
            </div>
            <span class="nav-link-text ms-1">Accepted Work</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="{{ route('works.finishedWorks') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">inventory</i>
            </div>
            <span class="nav-link-text ms-1">Finished Work</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="{{ route('admin.reporting') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">summarize</i>
            </div>
            <span class="nav-link-text ms-1">Reporting</span>
            </a>
        </li>
        <li class="nav-item mt-3">
            <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="{{ route('admin.landing') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">space_dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Landing Page Config</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="{{ route('services.index') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">category</i>
            </div>
            <span class="nav-link-text ms-1">Services and Categories</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="/customers">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">person</i>
            </div>
            <span class="nav-link-text ms-1">Customers List</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white " href="/employees">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">badge</i>
            </div>
            <span class="nav-link-text ms-1">Employee List</span>
            </a>
        </li>
        @endcan
    </ul>
</div>
</aside>